@import gg.jte.Content
@param Content content

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Some Bullshit</title>
</head>
<body>
<p>
<h2>Hello!</h2>
<a href="/users">Users</a>
<div></div>
<dov>---------</dov>
<dov></dov>
<a href="/">Main</a>
<footer>
    plain text
    ${content}
</footer>
</p>
</body>
</html>